name: CI Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    # 只构建 Docker 镜像，不推送
    - name: Build Docker image (local only)
      run: |
        docker build -t liveonchain-app:${{ github.sha }} .
        echo "✅ Docker 镜像构建成功，仅本地存储"

  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/main'
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /opt/tye-all-in-one/tye-all-in-one
          git pull origin main
          docker-compose -f docker-compose.local.yml down
          docker-compose -f docker-compose.local.yml build
          docker-compose -f docker-compose.local.yml up -d
